# Assignment 8 

1.	Write a Python Program to Add Two Matrices?


In [1]:

import numpy as np

X = [[1,2,3],
	[4 ,5,6],
	[7 ,8,9]]

Y = [[9,8,7],
	[6,5,4],
	[3,2,1]]

result = np.array(X) + np.array(Y)

print(result)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


2.	Write a Python Program to Multiply Two Matrices?


In [5]:
import numpy as np
A=[[1,2,3],
  [4,5,6],
  [7,8,9]]

B=[[7,8,9,1],
  [4,5,6,2],
  [1,2,3,3]]

result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]
result= np.dot(A,B)

for r in result:
    print(r)

[18 24 30 14]
[54 69 84 32]
[ 90 114 138  50]


3.	Write a Python Program to Transpose a Matrix?


In [6]:
matrix = [[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 3],
          [4, 4, 4, 4]]
print(np.transpose(matrix))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


4.	Write a Python Program to Sort Words in Alphabetic Order?


In [9]:
def F(S):
    W = S.split(" ")
    for i in range(len(W)):
        W[i] = W[i].lower()
    W.sort()
 
    # return the sorted words
    return ' '.join(W)
 
# Driver code
S = "humans for humaNs"
print(F(S))

for humans humans


5.	Write a Python Program to Remove Punctuation From a String?


In [12]:
import string

# initializing string
test_str = "ineuron, is best : for ! students ;"

print("The original string is : " + test_str)

# Removing punctuations using replace() method
for punctuation in string.punctuation:
	test_str = test_str.replace(punctuation, '')

# printing result
print("The string after punctuation filter : " + test_str)


The original string is : ineuron, is best : for ! students ;
The string after punctuation filter : ineuron is best  for  students 
